sql: pass a discovery to lasso to do watchability checks
rancher/steve pull request #263
Opened 2024-08-14 15:39 UTC by moio

Fixes https://github.com/rancher/rancher/issues/46030

Requires https://github.com/rancher/lasso/pull/93 to be merged (and lasso to be bumped here) before merging.

2024-08-14 15:59 UTC, MbolotSuse requested changes
One comment on error handling.

2024-08-14 15:59 UTC, MbolotSuse commented on pkg/stores/sqlproxy/proxy_store.go
I think we need to handle cases (like on L631) where the factor can't get a cache more gracefully now. My thinking is that if someone tries to list for this type and it's not watchable, either we need to return an error indicating that this endpoint can't be used (probably a [501](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501) error) or we should try to do an un-cached list and go from there. Either way I think we probably need a more detailed error handling mechanism there.

2024-08-14 16:06 UTC, moio commented on pkg/stores/sqlproxy/proxy_store.go
With this patch (and the accompanying steve one) we return error 500

I am in conversations with UI folks to see how this can be worked around in the few cases where we really need non-watchable but listable resources

2024-08-14 16:45 UTC, MbolotSuse commented on pkg/stores/sqlproxy/proxy_store.go
> we return error 500

I think that we should be a bit more specific than this - [500](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500) is a bit too generic for this condition, which we know isn't resolvable. 

> I am in conversations with UI folks to see how this can be worked around in the few cases where we really need non-watchable but listable resources

Sounds good, I'll leave this thread open until we have an idea of how our API contract should be formed. That being said, even in this original PR I think that we want to be more specific on the error code.

2024-08-21 10:10 UTC, moio commented on pkg/stores/sqlproxy/proxy_store.go
UI is OK with error 500.

In any case, this is expected to be temporary as we agreed to support listing unwatchable resources before the feature is turned on by default (https://github.com/rancher/rancher/issues/46768), so the error code will not matter for long - and at the moment error 500 already produces the right UI behavior (table reports "n/a" instead of the expected values).

2024-08-27 12:15 UTC, moio commented
See https://github.com/rancher/lasso/pull/93#issuecomment-2312401589

2024-08-27 12:15 UTC, closed without merging