refactor(accesscontrol): make addAccess directly accept PolicyRules
rancher/steve pull request #292
Opened 2024-10-09 09:21 UTC by aruiz14

## Issue: https://github.com/rancher/rancher/issues/47460

* Small refactoring of some internal functions to allow reusing them
* Add new types for encapsulating all needed data
* Make accessStore use the new types and method
* Cleanup unused code and adapt tests to new signatures
* Add new comments to structs and methods
* Refactor PolicyRules' indexer to make it easier to read and more testable

2024-10-09 19:49 UTC, ericpromislow commented on pkg/accesscontrol/policy_rule_index.go
> +// getRules obtain the actual Role or ClusterRole pointed at by a RoleRef, and returns PolicyRyles and the resource version
Typo: should be `PolicyRules`

2024-10-09 19:57 UTC, ericpromislow requested changes
Looks fine, apart from a trivial typo

2024-10-10 21:42 UTC, ericpromislow submitted a review, later dismissed
thx

2024-10-24 09:30 UTC, bigkevmcd submitted a review, later dismissed
I've gone over this in fine detail, and it looks fine.

It improves the test coverage a fair bit, but there's still a lot of untested code that we can address when we next touch these files.

2024-10-24 09:32 UTC, aruiz14 commented on pkg/accesscontrol/access_store.go
>  	as := &AccessStore{
I did not want to break the public interface

2024-10-24 13:49 UTC, aruiz14 commented
@ericpromislow please take another look, I've addressed Kevin's feedback but it didn't affect core of this PR.

2024-10-25 07:55 UTC, bigkevmcd approved these changes

2024-10-25 19:12 UTC, ericpromislow approved these changes
Works and looks ok

2024-10-28 08:35 UTC, merged