bump dynamic listener
rancher/steve pull request #313
Opened 2024-10-29 20:22 UTC by ericpromislow

Related to [#46957](https://github.com/rancher/rancher/issues/46957)

for v2.9.4

2024-10-30 08:46 UTC, aruiz14 requested changes

2024-10-30 08:46 UTC, aruiz14 commented on go.mod
> +	github.com/rancher/wrangler/v3 v3.0.1-rc.2
This tag includes a bump in the Kubernetes versions, which will be part of `3.1.0` instead.
Please use `v3.0.1-rc.4` instead.
cc/ @tomleb should we even remove that `v3.0.1-rc.2` tag?

2024-10-30 08:46 UTC, aruiz14 commented on go.mod
> +	k8s.io/kube-aggregator v0.31.1
This should not happen in 2.9, right? It's likely the culprit for the opentelemetry dependency conflicts

2024-11-12 18:49 UTC, tomleb commented
Please retarget this PR to the new branch: `release/v0.3`

2025-05-05 21:19 UTC, ericpromislow commented
This is obsolete. Bumping and dropping golang.org/mock happened elsewhere

2025-05-05 21:19 UTC, closed without merging