Cleanup and docs
rancher/steve pull request #60
Opened 2022-10-17 20:03 UTC by cmurphy

* Remove unused packages and functions
* Cleanup minor code quality issues
* Fix HTTP compliance
* Add godoc comments for the stores/partition and stores/proxy packages. This is to set up a base for significant alterations to how the base stores work with pagination, sorting, and filtering.

Partially addresses https://github.com/rancher/rancher/issues/38593

2022-10-18 21:29 UTC, rmweir approved these changes
LGTM

2022-10-19 15:05 UTC, MbolotSuse requested changes
Thanks for adding comments to a lot of this stuff.

I have some concerns about changing exported functions/interfaces on a non-major release. I'd prefer we not do this (or that we tag the code after this is merged as v1.0.0) - as we are not the only users of steve.

One other note - your CI is going to fail until #59 goes in. If you want it to pass, you can update a specific part of the .drone.yml to fix that - see [here](https://github.com/rancher/steve/pull/59/files#diff-b54b39f1afced2465e1f3641db9d5bbf4f3a7fcf890996dfedd3c197bcb7f8c7R11-R16) for what you need to add.

2022-10-19 17:27 UTC, cmurphy commented
@MbolotSuse I disagree about changing exported functions. steve does not follow semver. It does not even have releases. We don't make any guarantees of backwards compatibility. I've checked in harvester and throughout github and nothing is using these functions and packages. If I missed something, someone can file an issue and it is easy to revert. But I don't think trying to live up to an idealistic standard of API compatibility is helpful to us. It is more beneficial to clean up cruft because this helps us maintain the code in the long run.

2022-10-19 17:27 UTC, cmurphy commented on pkg/server/router/router.go
> +	m.Path("/").Handler(h.APIRoot).HeadersRegexp("Accept", ".*json.*")
https://github.com/rancher/dashboard/search?q=Accepts

2022-10-20 16:20 UTC, MbolotSuse commented
Discussed offline - since Steve doesn't currently follow a versioning strategy, there's no incentive for us to preserve functionality between changes. Especially when the functionality isn't being used by other areas.

2022-10-26 14:40 UTC, KevinJoiner approved these changes
"[s]he is a hero, not the hero we deserved but the hero we needed"
🙇‍♂️

2022-10-27 21:28 UTC, cmurphy commented
rebased

2022-10-31 18:25 UTC, merged