[WIP] Add support for OR filters
rancher/steve pull request #76
Opened 2023-02-16 23:41 UTC by cmurphy

https://github.com/rancher/rancher/issues/40141

Currently, multiple filters can be appended on the query string, and each subsequent filter is ANDed with the set. Items that pass through the filter set must match every filter in the set.

This change adds support for OR filters. A single filter key can specify multiple filters, separated by ','. An item that passes this filter can match any filter in the set.

For example, this filter matches items that have either "name" or "namespace" that match "example":

?filter=metadata.name=example,metadata.namespace=example

This filter matches items that have "name" that matches either "foo" or "bar":

?filter=metadata.name=foo,metadata.name=bar

Specifying more than one filter key in the query still ANDs each inner filter set together. This set of filters can match either a name of "foo" or "bar", but must in all cases match namespace "abc":

?filter=metadata.name=foo,metadata.name=bar&filter=metadata.namespace=abc

2023-03-20 20:00 UTC, KevinJoiner requested changes

2023-03-23 21:12 UTC, cmurphy commented on pkg/stores/partition/listprocessor/processor.go
> +}
:+1:

2023-03-23 21:12 UTC, cmurphy commented on pkg/stores/partition/listprocessor/processor.go
> +		}
:+1:

2023-03-27 13:56 UTC, KevinJoiner approved these changes

2023-03-29 23:33 UTC, rmweir approved these changes
LGTM

2023-03-30 11:45 UTC, merged